#
# Initialise DRC package. 
#
cv = ui().getEditCellView()
geomBegin(cv)
#
# Loading raw layers
#
nwell            = geomGetShapes("NWell", "drawing")
pwell_block      = geomGetShapes("PWell", "block")
nbulay           = geomGetShapes("nBuLay", "drawing")
nbulay_block     = geomGetShapes("nBuLay", "block")
activ            = geomGetShapes("Activ", "drawing")
activ_filler     = geomGetShapes("Activ", "filler")
thickgateox      = geomGetShapes("ThickGateOx", "drawing")
gatpoly          = geomGetShapes("GatPoly", "drawing")
gatpoly_filler   = geomGetShapes("GatPoly", "filler")
psd              = geomGetShapes("pSD", "drawing")
nsd              = geomGetShapes("nSD", "drawing")
nsd_block        = geomGetShapes("nSD", "block")
extblock         = geomGetShapes("EXTBlock", "drawing")
salblcok         = geomGetShapes("SalBlock", "drawing")
cont             = geomGetShapes("Cont", "drawing")
metal1           = geomGetShapes("Metal1", "drawing")
metal2           = geomGetShapes("Metal2", "drawing")
metal3           = geomGetShapes("Metal3", "drawing")
metal4           = geomGetShapes("Metal4", "drawing")
metal5           = geomGetShapes("Metal5", "drawing")
topmetal1        = geomGetShapes("TopMetal1", "drawing")
topmetal2        = geomGetShapes("TopMetal2", "drawing")
metal1_filler    = geomGetShapes("Metal1", "filler")
metal2_filler    = geomGetShapes("Metal2", "filler")
metal3_filler    = geomGetShapes("Metal3", "filler")
metal4_filler    = geomGetShapes("Metal4", "filler")
metal5_filler    = geomGetShapes("Metal5", "filler")
topmetal1_filler = geomGetShapes("TopMetal1", "filler")
topmetal2_filler = geomGetShapes("TopMetal2", "filler")
via1             = geomGetShapes("Via1", "drawing")
via2             = geomGetShapes("Via2", "drawing")
via3             = geomGetShapes("Via3", "drawing")
via4             = geomGetShapes("Via4", "drawing")
topvia1          = geomGetShapes("TopVia1", "drawing")
topvia2          = geomGetShapes("TopVia2", "drawing")
passiv_sbump     = geomGetShapes("Passiv", "sbump")
passiv_pillar    = geomGetShapes("Passiv", "pillar")
passiv           = geomGetShapes("Passiv", "drawing")
dpad             = geomGetShapes("dfpad", "drawing")
pwell            = geomGetShapes("PWell", "drawing")
trans            = geomGetShapes("TRANS", "drawing")
gatpoly_nofill   = geomGetShapes("GatPoly", "nofill")
res              = geomGetShapes("RES", "drawing")
edgeseal         = geomGetShapes("EdgeSeal", "drawing")
mim              = geomGetShapes("MIM", "drawing")
metal1_slit      = geomGetShapes("Metal1", "slit")
metal2_slit      = geomGetShapes("Metal2", "slit")
metal3_slit      = geomGetShapes("Metal3", "slit")
metal4_slit      = geomGetShapes("Metal4", "slit")
metal5_slit      = geomGetShapes("Metal5", "slit")
topmetal1_slit   = geomGetShapes("TopMetal1", "slit")
topmetal2_slit   = geomGetShapes("TopMetal2", "slit")
activ_pin        = geomGetShapes("Activ", "pin")
gatpoly_pin      = geomGetShapes("GatPoly", "pin")
metal1_pin       = geomGetShapes("Metal1", "pin")
metal2_pin       = geomGetShapes("Metal2", "pin")
metal3_pin       = geomGetShapes("Metal3", "pin")
metal4_pin       = geomGetShapes("Metal4", "pin")
metal5_pin       = geomGetShapes("Metal5", "pin")
topmetal1_pin    = geomGetShapes("TopMetal1", "pin")
topmetal2_pin    = geomGetShapes("TopMetal2", "pin")
digibnd          = geomGetShapes("DigiBnd", "drawing")
lbe              = geomGetShapes("LBE", "drawing")
#
# Forming derived layers
#
bkgnd       = geomBkgnd()
pwell       = geomOr(geomNot(geomOr(nwell, pwell_block)), pwell)
nbl         = geomAndNot(geomOr(geomSize(geomSize(nwell, -1.495), 0.495), nbulay), nbulay_block)
gate        = geomAnd(activ, gatpoly)
#diff       = geomAndNot(activ, gatpoly)
#ndiff      = geomAnd(diff, geomOr(nsd, geomNot(geomOr(psd, nsd_block))))
#pdiff      = geomAnd(diff, psd)
nactiv      = geomAnd(activ, geomOr(nsd, geomNot(geomOr(psd, nsd_block))))
pactiv      = geomAnd(activ, psd)
thickpactiv = geomInside(thickgateox, pactiv)
thicknactiv = geomInside(thickgateox, nactiv)
ntap        = geomContains(nwell, nactiv)
ptap        = geomContains(pwell, pactiv)
thickntap   = geomInside(thickgateox, ntap)
thickptap   = geomInside(thickgateox, ptap)
nfet        = geomAnd(nactiv, gate)
pfet        = geomContains(nwell, geomAnd(pactiv, gate))
hvnfet      = geomInside(thickgateox, nfet)
hvpfet      = geomInside(thickgateox, pfet)
pntap       = geomAnd(pactiv, nwell)
ncon        = geomAnd(nbl, nwell)
nres        = geomAnd(res, geomAndNot(gatpoly, psd))
pres        = geomAnd(geomAnd(gatpoly, salblcok), psd)
pnres       = geomAnd(geomAnd(gatpoly, salblcok), geomAnd(psd, nsd))
infet       = geomContains(geomContains(nbl, pwell), nfet)
hvinfet     = geomContains(geomContains(nbl, pwell), hvnfet)
cntbx       = geomSize(geomSize(cont, -0.08, horizontal), 0.08, horizontal)
cntby       = geomSize(geomSize(cont, -0.08, vertical), 0.08, vertical) 
cnt         = geomAndNot(cont, geomOr(cntbx, cntby))
schottky    = geomContains(geomContains(geomContains(geomContains(nbl, salblcok), nsd_block), pwell_block), geomOr(cntbx, cntby))
pad         = geomAnd(passiv, geomAnd(passiv_sbump, geomAnd(passiv_pillar, dpad)))
sbumppad    = geomAndNot(geomAnd(passiv_sbump, dpad), geomOr(passiv, passiv_pillar))
cupillarpad = geomAndNot(geomAnd(passiv_pillar, dpad), geomOr(passiv, passiv_sbump))
mimcap      = geomAnd(mim, metal5)
metal       = geomOr(metal1, geomOr(metal2, geomOr(metal3, geomOr(metal4, geomOr(metal5, geomOr(topmetal1, topmetal2))))))
metal_slit  = geomOr(metal1_slit, geomOr(metal2_slit, geomOr(metal3_slit, geomOr(metal4_slit, geomOr(metal5_slit, geomOr(topmetal1_slit, topmetal2_slit))))))
pin         = geomOr(activ_pin ,geomOr(gatpoly_pin ,geomOr(metal1_pin, geomOr(metal2_pin, geomOr(metal3_pin, geomOr(metal4_pin, geomOr(metal5_pin, geomOr(topmetal1_pin, topmetal2_pin))))))))
#
# Forming connectivity.
#
print("Extracting connectivity")
geomConnect( [
        [ncon, nbl, nwell],
        [ntap, nwell, nactiv],
        [ptap, pwell, pactiv],
        [cont, nactiv, pactiv, gatpoly, metal1],
        [via1, metal1, metal2],
        [via2, metal2, metal3],
        [via3, metal3, metal4],
        [via4, metal4, metal5],
        [topvia1, metal5, topmetal1],
        [topvia2, topmetal1, topmetal2],
        ] )
#
# Start design rule check
#
print("Checking off-grid geoemtries:")
geomOffGrid(nwell, 0.005, 0.1, "NWell off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(pwell_block, 0.005, 0.1, "PWell:block off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(nbulay, 0.005, 0.1, "nBuLay off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(nbulay_block, 0.005, 0.1, "nBuLay:block off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(activ, 0.005, 0.1, "Activ off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(activ_filler, 0.005, 0.1, "Activ:filler off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(thickgateox, 0.005, 0.1, "ThickGateOx off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(gatpoly, 0.005, 0.1, "GatPoly off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(gatpoly_filler, 0.005, 0.1, "GatPoly:filler off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(psd, 0.005, 0.1, "pSD off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(nsd, 0.005, 0.1, "nSD off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(nsd_block, 0.005, 0.1, "nSD:block off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(extblock, 0.005, 0.1, "EXTBlock off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(salblcok, 0.005, 0.1, "SalBlock off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(cont, 0.005, 0.1, "Cont off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal1, 0.005, 0.1, "Metal1 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal2, 0.005, 0.1, "Metal2 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal3, 0.005, 0.1, "Metal3 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal4, 0.005, 0.1, "Metal4 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal5, 0.005, 0.1, "Metal5 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(topmetal1, 0.005, 0.1, "TopMetal1 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(topmetal2, 0.005, 0.1, "TopMetal2 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal1_filler, 0.005, 0.1, "Metal1:filler off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal2_filler, 0.005, 0.1, "Metal2:filler off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal3_filler, 0.005, 0.1, "Metal3:filler off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal4_filler, 0.005, 0.1, "Metal4:filler off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal5_filler, 0.005, 0.1, "Metal5:filler off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(topmetal1_filler, 0.005, 0.1, "TopMetal1:filler off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(topmetal2_filler, 0.005, 0.1, "TopMetal2:filler off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(via1, 0.005, 0.1, "Via1 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(via2, 0.005, 0.1, "Via2 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(via3, 0.005, 0.1, "Via3 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(via4, 0.005, 0.1, "Via4 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(topvia1, 0.005, 0.1, "TopVia1 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(topvia2, 0.005, 0.1, "TopVia2 off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(passiv, 0.005, 0.1, "Passiv off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(pwell, 0.005, 0.1, "PWell off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(trans, 0.005, 0.1, "TRANS off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(gatpoly_nofill, 0.005, 0.1, "GatPoly:nofill off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(res, 0.005, 0.1, "RES off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(edgeseal, 0.005, 0.1, "EdgeSeal off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(mim, 0.005, 0.1, "MIM off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal1_slit, 0.005, 0.1, "Metal1:slit off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal2_slit, 0.005, 0.1, "Metal2:slit off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal3_slit, 0.005, 0.1, "Metal3:slit off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal4_slit, 0.005, 0.1, "Metal4:slit off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal5_slit, 0.005, 0.1, "Metal5:slit off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(topmetal1_slit, 0.005, 0.1, "TopMetal1:slit off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(topmetal2_slit, 0.005, 0.1, "TopMetal2:slit off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(activ_pin, 0.005, 0.1, "Activ:pin off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(gatpoly_pin, 0.005, 0.1, "GatPoly:pin off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal1_pin, 0.005, 0.1, "Metal1:pin off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal2_pin, 0.005, 0.1, "Metal2:pin off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal3_pin, 0.005, 0.1, "Metal3:pin off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal4_pin, 0.005, 0.1, "Metal4:pin off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(metal5_pin, 0.005, 0.1, "Metal5:pin off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(topmetal1_pin, 0.005, 0.1, "TopMetal1:pin off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(topmetal2_pin, 0.005, 0.1, "TopMetal2:pin off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(digibnd, 0.005, 0.1, "DigiBnd off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
geomOffGrid(lbe, 0.005, 0.1, "LBE off-grid, shape dimensions must be amultiple of 0.005um x 0.005um")
#
if geomNumShapes(nwell) > 0 :
    print("Checking NWell rules:")
    geomWidth(nwell, 0.62, "NW.a: Min. NWell width < 0.62um")
    geomSpace(nwell, 0.62, samenet, "NW.b: Min. NWell space or notch (same net) < 0.62um")
    geomNotch(nwell, 0.62, "NW.b: Min. NWell space or notch (same net) < 0.62um")
    geomSpace(nwell, 1.80, diffnet, "NW.b1: Min. PWell width between NWell regions (different net) < 1.8um")
    geomSpace(nwell, pwell_block, 1.80, diffnet, "NW.b1: Min. PWell width between NWell regions (different net) < 1.8um")
    geomEnclose(nwell, geomNotInside(thickgateox, pactiv), 0.31, "NW.c: Min. NWell enclosure of P+Activ not inside ThickGateOx < 0.31um")
    geomEnclose(nwell, geomNotInside(digibnd, thickpactiv), 0.62, "NW.c1: Min. NWell enclosure of P+Activ inside ThickGateOx < 0.62um")
    geomSpace(nwell, geomNotInside(thickgateox, nactiv), 0.31, "NW.d: Min. NWell space to external N+Activ not inside ThickGateOx < 0.31um")
    geomSpace(nwell, geomNotInside(digibnd, thicknactiv), 0.62, "NW.d1: Min. NWell space to external N+Activ inside ThickGateOx < 0.62um")
    geomEnclose(nwell, geomNotInside(thickgateox, ntap), 0.24, "NW.e: Min. NWell enclosure of NWell tie surrounded entirely by NWell in N+Activ not inside ThickGateOx < 0.24um")
    geomEnclose(nwell, geomNotInside(digibnd, thickntap), 0.62, "NW.e1: Min. NWell enclosure of NWell tie surrounded entirely by NWell in N+Activ inside ThickGateOx < 0.62um")
    geomSpace(nwell, geomNotInside(thickgateox, ptap), 0.24, "NW.f: Min. NWell space to substrate tie in P+Activ not inside ThickGateOx < 0.24um")
    geomSpace(nwell, geomNotInside(digibnd, thickptap), 0.62, "NW.f1:  Min. NWell space to substrate tie in P+Activ inside ThickGateOx < 0.62um")
#
if geomNumShapes(pwell_block) > 0 :
    print("Checking PWell:block rules:")
    geomWidth(pwell_block, 0.62, "PWB.a: Min. PWell:block width < 0.62um")
    geomSpace(pwell_block, 0.62, "PWB.b: Min. PWell:block space or notch < 0.62um")
    geomNotch(pwell_block, 0.62, "PWB.b: Min. PWell:block space or notch < 0.62um")
    geomSpace(pwell_block, nwell, 0.62, "PWB.c: Min. PWell:block space to unrelated NWell < 0.62um")
    geomOverlap(pwell_block, nwell, 0.00, "PWB.d: Min. PWell:block overlap of NWell < 0.00um")
    geomSpace(pwell_block, geomInside(pwell, geomNotInside(thickgateox, nactiv)), 0.31, "PWB.e: Min. PWell:block space to (N+Activ not inside ThickGateOx) in PWell < 0.31um")
    geomSpace(pwell_block, geomInside(pwell, thicknactiv), 0.62, "PWB.e1: Min. PWell:block space to (N+Activ inside ThickGateOx) in PWell < 0.62um")
    geomSpace(pwell_block, geomInside(pwell, geomNotInside(thickgateox, ptap)), 0.24, "PWB.f: Min. PWell:block space to (P+Activ not inside ThickGateOx) in PWell < 0.24um")
    geomSpace(pwell_block, geomInside(pwell, thickptap), 0.62, "PWB.f1: Min. PWell:block space to (P+Activ inside ThickGateOx) in PWell < 0.62um")
#
if geomNumShapes(nbl) > 0 :
    print("Checking nBuLay rules:")
    geomWidth(nbl, 1.00, "NBL.a: Min. nBuLay width < 1.00um")
    geomSpace(nbl, 1.50, samenet, "NBL.b: Min. nBuLay space or notch (same net) < 1.50um")
    geomNotch(nbl, 1.50, "NBL.b: Min. nBuLay space or notch (same net) < 1.50um")
    geomSpace(nbl, 3.20, diffnet, "NBL.c: Min. PWell width between nBuLay regions (different net) (Note 1) < 3.20um")
    geomSpace(nbl, geomTouching(nbl, pwell_block), 3.20, diffnet, "NBL.c: Min. PWell width between nBuLay regions (different net) (Note 1) < 3.20um")
    geomSpace(nbl, nwell, 2.20, diffnet, "NBL.d: Min. PWell width between nBuLay and NWell (different net) < 2.20um")
    geomSpace(nbl, geomTouching(nwell, pwell_block), 2.20, diffnet, "NBL.d: Min. PWell width between nBuLay and NWell (different net) < 2.20um")
    geomSpace(nbl, geomInside(pwell, nactiv), 1.00, "NBL.e: Min. nBuLay space to unrelated N+Activ < 1.00um")
    geomSpace(nbl, geomInside(pwell, pactiv), 0.50, "NBL.f: Min. nBuLay space to unrelated P+Activ < 0.50um")
#
if geomNumShapes(nbulay_block) > 0 :
    print("Checking nBuLay:block rules:")
    geomWidth(nbulay_block, 1.50, "NBLB.a: Min. nBuLay:block width < 1.50um")
    geomSpace(nbulay_block, 1.00, "NBLB.b: Min. nBuLay:block space or notch < 1.00um")
    geomNotch(nbulay_block, 1.00, "NBLB.b: Min. nBuLay:block space or notch < 1.00um")
    geomEnclose(nbl, nbulay_block, 1.00, "NBLB.c: Min. nBuLay enclosure of nBuLay:block < 1.00um")
    geomSpace(nbulay_block, nbl, 1.50, "NBLB.d: Min. nBuLay:block space to unrelated nBuLay < 1.50um")
#
if geomNumShapes(activ) > 0 :
    print("Checking Activ rules:")
    geomWidth(activ, 0.15, "Act.a: Min. Activ width < 0.15um")
    geomSpace(activ, 0.21, "Act.b: Min. Activ space or notch < 0.21um")
    geomNotch(activ, 0.21, "Act.b: Min. Activ space or notch < 0.21um")
    geomExtension(geomOr(nactiv, pactiv), gate, 0.23, "Act.c: Min. Activ drain/source extension < 0.23um")
    geomArea(activ, 0.122, lessthan, "Act.d: Min. Activ area (um^2) < 0.122um^2") 
    geomArea(geomHoles(activ), 0.15, lessthan, "Act.e: Min. Activ enclosed area (um^2) < 0.15um^2")
#
if geomNumShapes(activ_filler) > 0 :
    print("Checking Activ:filler rules:")
    saveDerived(geomSize(geomSize(activ_filler, -2.5), 2.5), "AFil.a: Max. Activ:filler width > 5.00um")
    geomWidth(activ_filler, 1.00, "AFil.a1: Min. Activ:filler width < 1.00um")
    geomSpace(activ_filler, 0.42, "AFil.b: Min. Activ:filler space < 0.42um")
    geomSpace(activ_filler, geomOr(cont, gatpoly), 1.10, "AFil.c: Min. Activ:filler space to Cont, GatPoly < 1.10um")
    geomSpace(activ_filler, activ, 0.42, "AFil.c1: Min. Activ:filler space to Activ < 0.42um")
    geomSpace(activ_filler, geomOr(nwell, nbl), 1.00, "AFil.d: Min. Activ:filler space to NWell, nBuLay < 1.00um")
    geomSpace(activ_filler, trans, 1.00, "AFil.e: Min. Activ:filler space to TRANS < 1.00um")
    geomMinDensity(activ_filler, 35.00, "AFil.g: Min. global Activ density [%] < 35.00%")
    geomMaxDensity(activ_filler, 55.00, "AFil.g1: Max. global Activ density [%] > 55.00%")
    geomDensity(activ_filler, 800.00, 800.00, 1.00, 1.00, 25.00, lessthan, "AFil.g2: Min. Activ coverage ratio for any 800 x 800µm2 chip area [%] < 25.00%")
    geomDensity(activ_filler, 800.00, 800.00, 1.00, 1.00, 65.00, greaterthan, "AFil.g3: Max. Activ coverage ratio for any 800 x 800µm2 chip area [%] > 65.00%")
    geomSpace(activ_filler, pwell_block, 1.50, "AFil.i: Min. Activ:filler space to edges of PWell:block < 1.50um")
    geomEnclose(pwell_block, activ_filler, 1.50, "AFil.i: Min. Activ:filler space to edges of PWell:block < 1.50um")
    geomEnclose(geomOr(nsd_blockx, nsd_block), geomInside(pwell_block, activ_filler), 0.25, "AFil.j: Min. nSD:block and SalBlock enclosure of Activ:filler inside PWell:block < 0.25um")
#
if geomNumShapes(thickgateox) > 0 :
    print("Checking ThickGateOxide rules:")
    geomExtension(thickgateox, geomOr(nactiv, pactiv), 0.27, "TGO.a: Min. ThickGateOx extension over Activ < 0.27um")
    geomSpace(thickgateox, geomOr(nactiv, pactiv), 0.27, "TGO.b: Min. space between ThickGateOx and Activ outside thick gateoxide region < 0.27um")
    geomExtension(thickgateox, gate, 0.34, "TGO.c: Min. ThickGateOx extension over GatPoly over Activ < 0.34um")
    geomSpace(thickgateox, gate, 0.34, "TGO.d: Min. space between ThickGateOx and GatPoly over Activ outside thick gate oxide region < 0.34um")
    geomSpace(thickgateox, 0.86, "TGO.e: Min. ThickGateOx space (merge if less than this value) < 0.86um")
    geomWidth(thickgateox, 0.86, "TGO.f: Min. ThickGateOx width < 0.86um")
#
if geomNumShapes(gatpoly) > 0 :
    print("Checking GatPoly rules:")
    geomWidth(gatpoly, 0.13, "Gat.a: Min. GatPoly width < 0.13um")
    geomWidth(nfet, 0.13, "Gat.a1: Min. GatPoly width for channel length of 1.2V NFET < 0.13um")
    geomWidth(pfet, 0.13, "Gat.a2: Min. GatPoly width for channel length of 1.2V PFET < 0.13um")
    geomLength(hvnfet, 0.45, "Gat.a3: Min. GatPoly width for channel length of 3.3V NFET < 0.45um")
    geomLength(hvpfet, 0.40, "Gat.a4: Min. GatPoly width for channel length of 3.3V PFET < 0.40um")
    geomSpace(gatpoly, 0.18, "Gat.b: Min. GatPoly space or notch < 0.18um")
    geomNotch(gatpoly, 0.18, "Gat.b: Min. GatPoly space or notch < 0.18um")
    geomSpace(geomOr(hvnfet, hvpfet), 0.25, "Gat.b1: Min. space between unrelated 3.3V GatPoly over Activ regions < 0.25um")
    geomExtension(gatpoly, gate, 0.18, "Gat.c: Min. GatPoly extension over Activ (end cap) < 0.18um")
    geomSpace(gatpoly, geomOr(nactiv, pactiv), 0.07, "Gat.d: Min. GatPoly space to Activ < 0.07um")
    geomArea(gatpoly, 0.09, lessthan, "Gat.e: Min. GatPoly area (um^2) < 0.09um^2") 
    saveDerived(geomGetPolygons(gate), "Gat.f: 45-degree and 90-degree angles for GatPoly on Activ area are not allowed")
    geomWidth(geomSize(geomGetNon90(gatpoly), -0.195, horizontal), 0.16, "Gat.g: Min. GatPoly width for 45-degree bent shapes if the bend GatPoly length is > 0.39um < 0.16um")
#
if geomNumShapes(gatpoly_filler) > 0 :
    print("Checking GatPoly:filler rules:")
    saveDerived(geomSize(geomSize(gatpoly_filler, -2.5), 2.5), "GFil.a: Max. GatPoly:filler width > 5.00um")
    geomWidth(gatpoly_filler, 0.70, "GFil.b: Min. GatPoly:filler width < 0.70um")
    geomSpace(gatpoly_filler, 0.80, "GFil.c: Min. GatPoly:filler space < 0.80um")
    geomSpace(gatpoly_filler, geomOr(nactiv, pactiv), 1.10, "GFil.d:  Min. GatPoly:filler space to Activ, GatPoly, Cont, pSD, nSD:block, SalBlock < 1.10um")
    geomSpace(gatpoly_filler, gatpoly, 1.10, "GFil.d: Min. GatPoly:filler space to Activ, GatPoly, Cont, pSD, nSD:block, SalBlock < 1.10um")
    geomSpace(gatpoly_filler, cont, 1.10, "GFil.d: Min. GatPoly:filler space to Activ, GatPoly, Cont, pSD, nSD:block, SalBlock < 1.10um")
    geomSpace(gatpoly_filler, psd, 1.10, "GFil.d: Min. GatPoly:filler space to Activ, GatPoly, Cont, pSD, nSD:block, SalBlock < 1.10um")
    geomSpace(gatpoly_filler, nsd_block, 1.10, "GFil.d: Min. GatPoly:filler space to Activ, GatPoly, Cont, pSD, nSD:block, SalBlock < 1.10um")
    geomSpace(gatpoly_filler, salblcok, 1.10, "GFil.d: Min. GatPoly:filler space to Activ, GatPoly, Cont, pSD, nSD:block, SalBlock < 1.10um")
    geomSpace(gatpoly_filler, nwell, 1.10, "GFil.e: Min. GatPoly:filler space to NWell, nBuLay < 1.10um")
    geomEnclose(nwell, gatpoly_filler, 1.10, "GFil.e: Min. GatPoly:filler space to NWell, nBuLay < 1.10um")
    geomSpace(gatpoly_filler, nbl, 1.10, "GFil.e: Min. GatPoly:filler space to NWell, nBuLay < 1.10um")
    geomEnclose(nbl, gatpoly_filler, 1.10, "GFil.e: Min. GatPoly:filler space to NWell, nBuLay < 1.10um")
    geomSpace(gatpoly_filler, trans, 1.10, "GFil.f: Min. GatPoly:filler space to TRANS < 1.10um")
    geomMinDensity(gatpoly_filler, 15.00, "GFil.g: Min. global GatPoly density [%] < 15.00%")
    geomArea(gatpoly_nofill, 0.16, greaterthan, "GFil.i: Max. GatPoly:nofill area (um^2) > 400x400um") 
    geomExtension(gatpoly_filler, activ_filler, 0.18, "GFil.j: Min. GatPoly:filler extension over Activ:filler (end cap) < 0.16um^2") 
#
if geomNumShapes(psd) > 0 :
    print("Checking pSD rules:")
    geomWidth(psd, 0.31, "pSD.a: Min.pSD width < 0.31um")
    geomSpace(psd, 0.31, "pSD.b: Min.pSD space or notch < 0.31um")
    geomNotch(psd, 0.31, "pSD.b: Min.pSD space or notch < 0.31um")
    geomEnclose(psd, pntap, 0.18, "pSD.c: Min. pSD enclosure of P+Activ in NWell < 0.18um")
    geomEnclose(psd, ptap, 0.03, "pSD.c1: Min. pSD enclosure of P+Activ in PWell < 0.03um")
    geomSpace(psd, geomInside(pwell, nactiv), 0.18, "pSD.d: Min. pSD space to unrelated N+Activ in PWell < 0.18um")
    geomSpace(psd, ntap, 0.03, "pSD.d1: Min. pSD space to N+Activ in NWell < 0.03um")
    geomOverlap(psd, pactiv, 0.30, "pSD.e: Min. pSD overlap of Activ at one position when forming abutted substratetie < 0.30um")
    geomExtension(geomInside(nwell, geomInteracts(psd, activ)), psd, 0.30, "pSD.f: Min. Activ extension over pSD at one position when forming abutted NWell tie < 0.30um")
    geomArea(geomOr(geomButting(nactiv, pactiv), geomButting(pactiv, nactiv)), 0.09, lessthan, "pSD.g: Min. N+Activ or P+Activ area (um^2) when forming abutted tie < 0.09um^2")
    geomEnclose(psd, geomNotInside(thickgateox, pfet), 0.30, "pSD.i: Min. pSD enclosure of PFET gate not inside ThickGateOx < 0.30um")
    geomEnclose(psd, hvpfet, 0.40, "pSD.i1: Min. pSD enclosure of PFET gate inside ThickGateOx < 0.40um")
    geomSpace(psd, geomNotInside(thickgateox, nfet), 0.30, "pSD.j: Min. pSD space to NFET gate not inside ThickGateOx < 0.30um")
    geomSpace(psd, hvnfet, 0.40, "pSD.j1: Min. pSD space to NFET gate inside ThickGateOx < 0.40um")
    geomArea(psd, 0.25, lessthan, "pSD.k: Min. pSD area (um^2) < 0.25um^2")
    geomArea(geomHoles(psd), 0.25, lessthan, "pSD.l: Min. pSD enclosed area (um^2) < 0.25um^2")
    geomSpace(psd, nres, 0.18, "pSD.m: Min. pSD space to n-type poly resistors < 0.18um")
    geomEnclose(psd, pres, 0.18, "pSD.n: Min. pSD enclosure of p-type poly resistors < 0.18um")
#
if geomNumShapes(nsd_block) > 0 :
    print("Checking nSD:block rules:")
    geomWidth(nsd_block, 0.31, "nSDB.a: Min. nSD:block width < 0.31um")
    geomSpace(nsd_block, 0.31, "nSDB.b: Min. nSD:block space or notch < 0.31um")
    geomNotch(nsd_block, 0.31, "nSDB.b: Min. nSD:block space or notch < 0.31um")
    geomSpace(nsd_block, psd, 0.31, "nSDB.c: Min. nSD:block space to unrelated pSD < 0.31um")
    geomOverlap(nsd_block, psd, 0.00, "nSDB.d: Min. nSD:block overlap of pSD < 0.00um")
    saveDerived(geomAnd(nsd_block, geomAndNot(cont, schottky)), "nSDB.e: Min. nSD:block space to Cont (nSD:block and Cont do not overlap) < 0.00um")
#
if geomNumShapes(extblock) > 0 :
    print("Checking EXTBlock rules:")
    geomWidth(extblock, 0.31, "EXTB.a: Min. EXTBlock width < 0.31um")
    geomSpace(extblock, 0.31, "EXTB.b: Min. EXTBlock space or notch < 0.31um")
    geomNotch(extblock, 0.31, "EXTB.b: Min. Min. EXTBlock space or notch < 0.31um")
    geomSpace(extblock, psd, 0.31, "EXTB.c: Min. EXTBlock space to pSD < 0.31um")
#
if geomNumShapes(salblcok) > 0 :
    print("Checking SalBlock rules:")
    geomWidth(salblcok, 0.42, "Sal.a: Min. SalBlock width < 0.42um")
    geomSpace(salblcok, 0.42, "Sal.b: Min. SalBlock space or notch < 0.42um")
    geomNotch(salblcok, 0.42, "Sal.b: Min. SalBlock space or notch < 0.42um")
    geomExtension(salblcok, geomOr(geomOr(nactiv, pactiv), gatpoly), 0.20, "Sal.c: Min. SalBlock extension over Activ or GatPoly < 0.20um")
    geomSpace(salblcok, geomOr(geomOr(nactiv, pactiv), gatpoly), 0.20, "Sal.d: Min. SalBlock space to unrelated Activ or GatPoly < 0.20um")
    geomSpace(salblcok, cont, 0.20, "Sal.e: Min. SalBlock space to Cont < 0.20um")
#
if geomNumShapes(cont) > 0 :
    if geomNumShapes(cnt) > 0 :
        print("Checking Cont rules:")
        geomAllowedSize(cnt, [[0.16, 0.16]], "Cnt.a: Min. and max. Cont width != 0.16um")
        geomSpace(cnt, 0.18, "Cnt.b: Min. Cont space < 0.18um")
        cnta = geomSize(cnt, 0.099)
        cnta = geomSize(cnta, -0.179)
        cnta = geomSize(cnta, 0.08)
        cnta = geomSize(cnta, -0.59)
        cnta = geomSize(cnta, 0.59)
        saveDerived(cnta, "Cnt.b1: Min. Cont space in a contact array of more than 4 rows and more then 4 columns < 0.20um")
        geomEnclose(geomOr(nactiv, pactiv), geomAndNot(cnt, digibnd), 0.07, "Cnt.c: Min. Activ enclosure of Cont < 0.07um")
        geomEnclose(gatpoly, cnt, 0.07, "Cnt.d: Min. GatPoly enclosure of Cont < 0.07um")
        geomSpace(geomAnd(cnt, gatpoly), geomOr(nactiv, pactiv), 0.14, "Cnt.e: Min. Cont on GatPoly space to Activ < 0.14um")
        geomSpace(geomAnd(cnt, geomOr(nactiv, pactiv)), gatpoly, 0.11, "Cnt.f: Min. Cont on Activ space to GatPoly < 0.11um")
        saveDerived(geomAndNot(cnt, geomOr(geomOr(nactiv, pactiv), gatpoly)), "Cnt.g: Cont must be within Activ or GatPoly")
        geomSpace(geomAnd(cnt, nactiv), psd, 0.09, "Cnt.g1: Min. pSD space to Cont on nSD-Activ < 0.09um")
        geomOverlap(psd, geomAnd(cnt, pactiv), 0.09, "Cnt.g2: Min. pSD overlap of Cont on pSD-Activ < 0.09um")
        saveDerived(geomAndNot(cnt, metal1), "Cnt.h: Cont must be covered with Metal1")
        saveDerived(geomAnd(cnt, gate), "Cnt.j: Cont on GatPoly over Activ is not allowed")
    #
    if ((geomNumShapes(cntbx) > 0) or (geomNumShapes(cntby) > 0)) :
        print("Checking ContBar rules:")
        geomAllowedWidths(cntbx, [0.16], horizontal | vertical, "CntB.a: Min. and max. ContBar width != 0.16um")
        geomAllowedWidths(cntby, [0.16], horizontal | vertical, "CntB.a: Min. and max. ContBar width != 0.16um")
        geomLength(cntbx, 0.34, "CntB.a1: Min. ContBar length = 0.34um") 
        geomLength(cntby, 0.34, "CntB.a1: Min. ContBar length = 0.34um") 
        geomSpace(cntbx, 0.28, "CntB.b: Min. ContBar space < 0.28um")
        geomSpace(cntby, 0.28, "CntB.b: Min. ContBar space < 0.28um")
        geomSpace2(cntbx, 0.36, 0.16, 5.00, horizontal, "CntB.b1: Min. ContBar space with common run > 5um < 0.36um")
        geomSpace2(cntby, 0.36, 0.16, 5.00, vertical, "CntB.b1: Min. ContBar space with common run > 5um < 0.36um")
        geomSpace(cntbx, cnt, 0.22, "CntB.b2: Min. ContBar space to Cont < 0.22um")
        geomSpace(cntby, cnt, 0.22, "CntB.b2: Min. ContBar space to Cont < 0.22um")
        geomEnclose(geomOr(nactiv, pactiv), cntbx, 0.07, "CntB.c: Min. Activ enclosure of ContBar < 0.07um")
        geomEnclose(geomOr(nactiv, pactiv), cntby, 0.07, "CntB.c: Min. Activ enclosure of ContBar < 0.07um")
        geomEnclose(gatpoly, cntbx, 0.07, "CntB.d: Min. GatPoly enclosure of ContBar < 0.07um")
        geomEnclose(gatpoly, cntby, 0.07, "CntB.d: Min. GatPoly enclosure of ContBar < 0.07um")
        geomSpace(geomAnd(cntbx, gatpoly), geomOr(nactiv, pactiv), 0.14, "CntB.e: Min. ContBar on GatPoly space to Activ < 0.14um")
        geomSpace(geomAnd(cntby, gatpoly), geomOr(nactiv, pactiv), 0.14, "CntB.e: Min. ContBar on GatPoly space to Activ < 0.14um")
        geomSpace(geomAnd(cntbx, geomOr(nactiv, pactiv)), gatpoly, 0.11, "CntB.f: Min. ContBar on Activ space to GatPoly < 0.11um")
        geomSpace(geomAnd(cntby, geomOr(nactiv, pactiv)), gatpoly, 0.11, "CntB.f: Min. ContBar on Activ space to GatPoly < 0.11um")
        saveDerived(geomAndNot(geomAndNot(cntbx, schottky), geomOr(nactiv, pactiv)), "CntB.g: ContBar must be within Activ or GatPoly")
        saveDerived(geomAndNot(geomAndNot(cntbx, schottky), geomOr(nactiv, pactiv)), "CntB.g: ContBar must be within Activ or GatPoly")
        geomSpace(geomAnd(cntbx, nactiv), psd, 0.09, "CntB.g1: Min. pSD space to ContBar on nSD-Activ < 0.09um")
        geomSpace(geomAnd(cntby, nactiv), psd, 0.09, "CntB.g1: Min. pSD space to ContBar on nSD-Activ < 0.09um")
        geomOverlap(psd, geomAnd(cntbx, pactiv), 0.09, "CntB.g2: Min. pSD overlap of ContBar on pSD-Activ < 0.09um")
        geomOverlap(psd, geomAnd(cntby, pactiv), 0.09, "CntB.g2: Min. pSD overlap of ContBar on pSD-Activ < 0.09um")
        saveDerived(geomAndNot(cntbx, metal1), "CntB.h: ContBar must be covered with Metal1")
        saveDerived(geomAndNot(cntby, metal1), "CntB.h: ContBar must be covered with Metal1")
        geomEnclose(metal1, cntbx, 0.05, "CntB.h1: Min. Metal1 enclosure of ContBar < 0.05um")
        geomEnclose(metal1, cntby, 0.05, "CntB.h1: Min. Metal1 enclosure of ContBar < 0.05um")
        saveDerived(geomAnd(cntbx, gate), "CntB.j: ContBar on GatPoly over Activ is not allowed")
        saveDerived(geomAnd(cntby, gate), "CntB.j: ContBar on GatPoly over Activ is not allowed")
#
if geomNumShapes(metal1) > 0 :
    print("Checking Metal1 rules:")
    geomWidth(metal1, 0.16, "M1.a: Min. Metal1 width < 0.16um")
    geomSpace(metal1, 0.18, "M1.b: Min. Metal1 space or notch < 0.18um")
    geomNotch(metal1, 0.18, "M1.b: Min. Metal1 space or notch < 0.18um")
    geomEnclose(metal1, cont, 0.00, "M1.c: Min. Metal1 enclosure of Cont < 0.00um")
    geomExtension(metal1, cont, 0.05, "M1.c1: Min. Metal1 endcap enclosure of Cont < 0.05um")
    geomArea(metal1, 0.09, lessthan, "M1.d: Min. Metal1 area (um^2) < 0.09um^2")
    geomSpace(metal1, 0.22, 0.30, 1.00, parallel, "M1.e: Min. space of Metal1 lines if, at least one line is wider than 0.3um and the parallel run is more than 1.0um < 0.22um")
    geomSpace(metal1, 0.60, 10.00, 10.00, parallel, "M1.f: Min. space of Metal1 lines if, at least one line is wider than 10.0um and the parallel run is more than 10.0um < 0.60um")
    xm1 = geomSize(geomGetNon90(metal1), -0.5, horizontal)
    ym1 = geomSize(geomGetNon90(metal1), -0.5, vertical)
    geomWidth(xm1, 0.20, "M1.g: Min. 45-degree bent Metal1 width if the bent metal length is > 0.5um < 0.20um")
    geomWidth(ym1, 0.20, "M1.g: Min. 45-degree bent Metal1 width if the bent metal length is > 0.5um < 0.20um")
    geomSpace(xm1, 0.22, "M1.i: Min. space of Metal1 lines of which at least one is bent by 45-degree < 0.22um")
    geomSpace(ym1, 0.22, "M1.i: Min. space of Metal1 lines of which at least one is bent by 45-degree < 0.22um")
    geomMinDensity(metal1, 35.00, "M1.j: Min. global Metal1 density [%] < 35.00%")
    geomMaxDensity(metal1, 60.00, "M1.k: Max. global Metal1 density [%] > 60.00%")
#
if geomNumShapes(metal2) > 0 :
    print("Checking Metal2 rules:")
    geomWidth(metal2, 0.20, "M2.a: Min. Metal2 width < 0.20um")
    geomSpace(metal2, 0.21, "M2.b: Min. Metal2 space or notch < 0.21um")
    geomNotch(metal2, 0.21, "M2.b: Min. Metal2 space or notch < 0.21um")
    geomEnclose(metal2, via1, 0.005, "M2.c: Min. Metal2 enclosure of Via1 < 0.005um")
    geomExtension(metal2, via1, 0.05, "M2.c1: Min. Metal2 endcap enclosure of Cont < 0.05um")
    geomArea(metal2, 0.144, lessthan, "M2.d: Min. Metal2 area (um^2) < 0.144um^2")
    geomSpace(metal2, 0.24, 0.39, 1.00, parallel, "M2.e: Min. space of Metal2 lines if, at least one line is wider than 0.39um and the parallel run is more than 1.0um < 0.24um")
    geomSpace(metal2, 0.60, 10.00, 10.00, parallel, "M2.f: Min. space of Metal2 lines if, at least one line is wider than 10.0um and the parallel run is more than 10.0um < 0.60um")
    xm2 = geomSize(geomGetNon90(metal2), -0.5, horizontal)
    ym2 = geomSize(geomGetNon90(metal2), -0.5, vertical)
    geomWidth(xm2, 0.24, "M2.g: Min. 45-degree bent Metal2 width if the bent metal length is > 0.5um < 0.24um")
    geomWidth(ym2, 0.24, "M2.g: Min. 45-degree bent Metal2 width if the bent metal length is > 0.5um < 0.24um")
    geomSpace(xm2, 0.24, "M2.i: Min. space of Metal2 lines of which at least one is bent by 45-degree < 0.24um")
    geomSpace(ym2, 0.24, "M2.i: Min. space of Metal2 lines of which at least one is bent by 45-degree < 0.24um")
    geomMinDensity(metal2, 35.00, "M2.j: Min. global Metal2 density [%] < 35.00%")
    geomMaxDensity(metal2, 60.00, "M2.k: Max. global Metal2 density [%] > 60.00%")
#
if geomNumShapes(metal3) > 0 :
    print("Checking Metal3 rules:")
    geomWidth(metal3, 0.20, "M3.a: Min. Metal3 width < 0.20um")
    geomSpace(metal3, 0.21, "M3.b: Min. Metal3 space or notch < 0.21um")
    geomNotch(metal3, 0.21, "M3.b: Min. Metal3 space or notch < 0.21um")
    geomEnclose(metal3, via2, 0.005, "M3.c: Min. Metal3 enclosure of Via2 < 0.005um")
    geomExtension(metal3, via2, 0.05, "M3.c1: Min. Metal3 endcap enclosure of Cont < 0.05um")
    geomArea(metal3, 0.144, lessthan, "M3.d: Min. Metal3 area (um^2) < 0.144um^2")
    geomSpace(metal3, 0.24, 0.39, 1.00, parallel, "M3.e: Min. space of Metal3 lines if, at least one line is wider than 0.39um and the parallel run is more than 1.0um < 0.24um")
    geomSpace(metal3, 0.60, 10.00, 10.00, parallel, "M3.f: Min. space of Metal3 lines if, at least one line is wider than 10.0um and the parallel run is more than 10.0um < 0.60um")
    xm3 = geomSize(geomGetNon90(metal3), -0.5, horizontal)
    ym3 = geomSize(geomGetNon90(metal3), -0.5, vertical)
    geomWidth(xm3, 0.24, "M3.g: Min. 45-degree bent Metal3 width if the bent metal length is > 0.5um < 0.24um")
    geomWidth(ym3, 0.24, "M3.g: Min. 45-degree bent Metal3 width if the bent metal length is > 0.5um < 0.24um")
    geomSpace(xm3, 0.24, "M3.i: Min. space of Metal3 lines of which at least one is bent by 45-degree < 0.24um")
    geomSpace(ym3, 0.24, "M3.i: Min. space of Metal3 lines of which at least one is bent by 45-degree < 0.24um")
    geomMinDensity(metal3, 35.00, "M3.j: Min. global Metal3 density [%] < 35.00%")
    geomMaxDensity(metal3, 60.00, "M3.k: Max. global Metal3 density [%] > 60.00%")
#
if geomNumShapes(metal4) > 0 :
    print("Checking Metal4 rules:")
    geomWidth(metal4, 0.20, "M4.a: Min. Metal4 width < 0.20um")
    geomSpace(metal4, 0.21, "M4.b: Min. Metal4 space or notch < 0.21um")
    geomNotch(metal4, 0.21, "M4.b: Min. Metal4 space or notch < 0.21um")
    geomEnclose(metal4, via3, 0.005, "M4.c: Min. Metal4 enclosure of Via3 < 0.005um")
    geomExtension(metal4, via3, 0.05, "M4.c1: Min. Metal4 endcap enclosure of Cont < 0.05um")
    geomArea(metal4, 0.144, lessthan, "M4.d: Min. Metal4 area (um^2) < 0.144um^2")
    geomSpace(metal4, 0.24, 0.39, 1.00, parallel, "M4.e: Min. space of Metal4 lines if, at least one line is wider than 0.39um and the parallel run is more than 1.0um < 0.24um")
    geomSpace(metal4, 0.60, 10.00, 10.00, parallel, "M4.f: Min. space of Metal4 lines if, at least one line is wider than 10.0um and the parallel run is more than 10.0um < 0.60um")
    xm4 = geomSize(geomGetNon90(metal4), -0.5, horizontal)
    ym4 = geomSize(geomGetNon90(metal4), -0.5, vertical)
    geomWidth(xm4, 0.24, "M4.g: Min. 45-degree bent Metal4 width if the bent metal length is > 0.5um < 0.24um")
    geomWidth(ym4, 0.24, "M4.g: Min. 45-degree bent Metal4 width if the bent metal length is > 0.5um < 0.24um")
    geomSpace(xm4, 0.24, "M4.i: Min. space of Metal4 lines of which at least one is bent by 45-degree < 0.24um")
    geomSpace(ym4, 0.24, "M4.i: Min. space of Metal4 lines of which at least one is bent by 45-degree < 0.24um")
    geomMinDensity(metal4, 35.00, "M4.j: Min. global Metal4 density [%] < 35.00%")
    geomMaxDensity(metal4, 60.00, "M4.k: Max. global Metal4 density [%] > 60.00%")
#
if geomNumShapes(metal5) > 0 :
    print("Checking Metal5 rules:")
    geomWidth(metal5, 0.20, "M5.a: Min. Metal5 width < 0.20um")
    geomSpace(metal5, 0.21, "M5.b: Min. Metal5 space or notch < 0.21um")
    geomNotch(metal5, 0.21, "M5.b: Min. Metal5 space or notch < 0.21um")
    geomEnclose(metal5, via4, 0.005, "M5.c: Min. Metal5 enclosure of Via4 < 0.005um")
    geomExtension(metal5, via4, 0.05, "M5.c1: Min. Metal5 endcap enclosure of Cont < 0.05um")
    geomArea(metal5, 0.144, lessthan, "M5.d: Min. Metal5 area (um^2) < 0.144um^2")
    geomSpace(metal5, 0.24, 0.39, 1.00, parallel, "M5.e: Min. space of Metal5 lines if, at least one line is wider than 0.39um and the parallel run is more than 1.0um < 0.24um")
    geomSpace(metal5, 0.60, 10.00, 10.00, parallel, "M5.f: Min. space of Metal5 lines if, at least one line is wider than 10.0um and the parallel run is more than 10.0um < 0.60um")
    xm5 = geomSize(geomGetNon90(metal5), -0.5, horizontal)
    ym5 = geomSize(geomGetNon90(metal5), -0.5, vertical)
    geomWidth(xm5, 0.24, "M5.g: Min. 45-degree bent Metal5 width if the bent metal length is > 0.5um < 0.24um")
    geomWidth(ym5, 0.24, "M5.g: Min. 45-degree bent Metal5 width if the bent metal length is > 0.5um < 0.24um")
    geomSpace(xm5, 0.24, "M5.i: Min. space of Metal5 lines of which at least one is bent by 45-degree < 0.24um")
    geomSpace(ym5, 0.24, "M5.i: Min. space of Metal5 lines of which at least one is bent by 45-degree < 0.24um")
    geomMinDensity(metal5, 35.00, "M5.j: Min. global Metal5 density [%] < 35.00%")
    geomMaxDensity(metal5, 60.00, "M5.k: Max. global Metal5 density [%] > 60.00%")
#
if geomNumShapes(metal1_filler) > 0 :
    print("Checking Metal1:filler rules:")
    geomWidth(metal1_filler, 1.00, "MFil.a1: Min. Metal1:filler width < 1.00um")
    saveDerived(geomSize(geomSize(metal1_filler, -2.5, horizontal), 2.5, horizontal), "MFil.a2: Max. Metal1:filler width > 5.00um")
    saveDerived(geomSize(geomSize(metal1_filler, -2.5, vertical), 2.5, vertical), "MFil.a2: Max. Metal1:filler width > 5.00um")
    geomSpace(metal1_filler, 0.42, "MFil.b: Min. Metal1:filler space < 0.42um")
    geomSpace(metal1_filler, metal1, 0.42, "MFil.c: Min. Metal1:filler space to Metal1 < 0.42um")
    geomSpace(metal1_filler, trans, 1.00, "MFil.d: Min. Metal1:filler space to TRANS < 1.00um")
    geomDensity(geomOr(metal1, metal1_filler), 800.00, 800.00, 1.00, 1.00, 25.00, lessthan, "MFil.h: Min. Metal1 and Metal1:filler coverage ratio for any 800 x 800um^2 chip area [%] < 25.00%")
    geomDensity(geomOr(metal1, metal1_filler), 800.00, 800.00, 1.00, 1.00, 75.00, greaterthan, "MFil.k: Max. Metal1 and Metal1:filler coverage ratio for any 800 x 800um^2 chip area [%] > 75.00%")
#
if geomNumShapes(metal2_filler) > 0 :
    print("Checking Metal2:filler rules:")
    geomWidth(metal2_filler, 1.00, "MFil.a1: Min. Metal2:filler width < 1.00um")
    saveDerived(geomSize(geomSize(metal2_filler, -2.5, horizontal), 2.5, horizontal), "MFil.a2: Max. Metal2:filler width > 5.00um")
    saveDerived(geomSize(geomSize(metal2_filler, -2.5, vertical), 2.5, vertical), "MFil.a2: Max. Metal2:filler width > 5.00um")
    geomSpace(metal2_filler, 0.42, "MFil.b: Min. Metal2:filler space < 0.42um")
    geomSpace(metal2_filler, metal2, 0.42, "MFil.c: Min. Metal2:filler space to Metal2 < 0.42um")
    geomSpace(metal2_filler, trans, 1.00, "MFil.d: Min. Metal2:filler space to TRANS < 1.00um")
    geomDensity(geomOr(metal2, metal2_filler), 800.00, 800.00, 1.00, 1.00, 25.00, lessthan, "MFil.h: Min. Metal2 and Metal2:filler coverage ratio for any 800 x 800um^2 chip area [%] < 25.00%")
    geomDensity(geomOr(metal2, metal2_filler), 800.00, 800.00, 1.00, 1.00, 75.00, greaterthan, "MFil.k: Max. Metal2 and Metal2:filler coverage ratio for any 800 x 800um^2 chip area [%] > 75.00%")
#
if geomNumShapes(metal3_filler) > 0 :
    print("Checking Metal3:filler rules:")
    geomWidth(metal3_filler, 1.00, "MFil.a1: Min. Metal3:filler width < 1.00um")
    saveDerived(geomSize(geomSize(metal3_filler, -2.5, horizontal), 2.5, horizontal), "MFil.a2: Max. Metal3:filler width > 5.00um")
    saveDerived(geomSize(geomSize(metal3_filler, -2.5, vertical), 2.5, vertical), "MFil.a2: Max. Metal3:filler width > 5.00um")
    geomSpace(metal3_filler, 0.42, "MFil.b: Min. Metal3:filler space < 0.42um")
    geomSpace(metal3_filler, metal3, 0.42, "MFil.c: Min. Metal3:filler space to Metal3 < 0.42um")
    geomSpace(metal3_filler, trans, 1.00, "MFil.d: Min. Metal3:filler space to TRANS < 1.00um")
    geomDensity(geomOr(metal3, metal3_filler), 800.00, 800.00, 1.00, 1.00, 25.00, lessthan, "MFil.h: Min. Metal3 and Metal3:filler coverage ratio for any 800 x 800um^2 chip area [%] < 25.00%")
    geomDensity(geomOr(metal3, metal3_filler), 800.00, 800.00, 1.00, 1.00, 75.00, greaterthan, "MFil.k: Max. Metal3 and Metal3:filler coverage ratio for any 800 x 800um^2 chip area [%] > 75.00%")
#
if geomNumShapes(metal4_filler) > 0 :
    print("Checking Metal4:filler rules:")
    geomWidth(metal4_filler, 1.00, "MFil.a1: Min. Metal4:filler width < 1.00um")
    saveDerived(geomSize(geomSize(metal4_filler, -2.5, horizontal), 2.5, horizontal), "MFil.a2: Max. Metal4:filler width > 5.00um")
    saveDerived(geomSize(geomSize(metal4_filler, -2.5, vertical), 2.5, vertical), "MFil.a2: Max. Metal4:filler width > 5.00um")
    geomSpace(metal4_filler, 0.42, "MFil.b: Min. Metal4:filler space < 0.42um")
    geomSpace(metal4_filler, metal4, 0.42, "MFil.c: Min. Metal4:filler space to Metal4 < 0.42um")
    geomSpace(metal4_filler, trans, 1.00, "MFil.d: Min. Metal4:filler space to TRANS < 1.00um")
    geomDensity(geomOr(metal4, metal4_filler), 800.00, 800.00, 1.00, 1.00, 25.00, lessthan, "MFil.h: Min. Metal4 and Metal4:filler coverage ratio for any 800 x 800um^2 chip area [%] < 25.00%")
    geomDensity(geomOr(metal4, metal4_filler), 800.00, 800.00, 1.00, 1.00, 75.00, greaterthan, "MFil.k: Max. Metal4 and Metal4:filler coverage ratio for any 800 x 800um^2 chip area [%] > 75.00%")
#
if geomNumShapes(metal5_filler) > 0 :
    print("Checking Metal5:filler rules:")
    geomWidth(metal5_filler, 1.00, "MFil.a1: Min. Metal5:filler width < 1.00um")
    saveDerived(geomSize(geomSize(metal5_filler, -2.5, horizontal), 2.5, horizontal), "MFil.a2: Max. Metal5:filler width > 5.00um")
    saveDerived(geomSize(geomSize(metal5_filler, -2.5, vertical), 2.5, vertical), "MFil.a2: Max. Metal5:filler width > 5.00um")
    geomSpace(metal5_filler, 0.42, "MFil.b: Min. Metal5:filler space < 0.42um")
    geomSpace(metal5_filler, metal5, 0.42, "MFil.c: Min. Metal5:filler space to Metal5 < 0.42um")
    geomSpace(metal5_filler, trans, 1.00, "MFil.d: Min. Metal5:filler space to TRANS < 1.00um")
    geomDensity(geomOr(metal5, metal5_filler), 800.00, 800.00, 1.00, 1.00, 25.00, lessthan, "MFil.h: Min. Metal5 and Metal5:filler coverage ratio for any 800 x 800um^2 chip area [%] < 25.00%")
    geomDensity(geomOr(metal5, metal5_filler), 800.00, 800.00, 1.00, 1.00, 75.00, greaterthan, "MFil.k: Max. Metal5 and Metal5:filler coverage ratio for any 800 x 800um^2 chip area [%] > 75.00%")
#
if geomNumShapes(via1) > 0 :
    print("Checking Via1 rules:")
    geomAllowedSize(via1, [[0.19, 0.19]], "V1.a: Min. and max. Via1 width != 0.19um")
    geomSpace(via1, 0.22, "V1.b: Min. Via1 space < 0.22um")
    v1 = geomSize(via1, 0.143)
    v1 = geomSize(v1, -0.238)
    v1 = geomSize(v1, 0.095)
    v1 = geomSize(v1, -0.505)
    v1 = geomSize(v1, 0.505)
    saveDerived(v1, "V1.b1: Min. Via1 space in an array of more than 3 rows and more then 3 columns  < 0.29um")
    geomEnclose(metal1, via1, 0.01, "V1.c: Min. Metal1 enclosure of Via1 < 0.01um")
    geomExtension(metal1, via1, 0.05, "V1.c1: Min. Metal1 endcap enclosure of Via1 < 0.05um")
#
if geomNumShapes(via2) > 0 :
    print("Checking Via2 rules:")
    geomAllowedSize(via2, [[0.19, 0.19]], "V2.a: Min. and max. Via2 width != 0.19um")
    geomSpace(via2, 0.22, "V2.b: Min. Via2 space < 0.22um")
    v2 = geomSize(via2, 0.143)
    v2 = geomSize(v2, -0.238)
    v2 = geomSize(v2, 0.095)
    v2 = geomSize(v2, -0.505)
    v2 = geomSize(v2, 0.505)
    saveDerived(v2, "V2.b1: Min. Via2 space in an array of more than 3 rows and more then 3 columns  < 0.29um")
    geomEnclose(metal2, via2, 0.005, "V2.c: Min. Metal2 enclosure of Via2 < 0.005um")
    geomExtension(metal2, via2, 0.05, "V2.c1: Min. Metal2 endcap enclosure of Via2 < 0.05um")
#
if geomNumShapes(via3) > 0 :
    print("Checking Via3 rules:")
    geomAllowedSize(via3, [[0.19, 0.19]], "V3.a: Min. and max. Via3 width != 0.19um")
    geomSpace(via3, 0.22, "V3.b: Min. Via3 space < 0.22um")
    v3 = geomSize(via3, 0.143)
    v3 = geomSize(v3, -0.238)
    v3 = geomSize(v3, 0.095)
    v3 = geomSize(v3, -0.505)
    v3 = geomSize(v3, 0.505)
    saveDerived(v3, "V3.b1: Min. Via3 space in an array of more than 3 rows and more then 3 columns  < 0.29um")
    geomEnclose(metal3, via3, 0.005, "V3.c: Min. Metal3 enclosure of Via3 < 0.005um")
    geomExtension(metal3, via3, 0.05, "V3.c1: Min. Metal3 endcap enclosure of Via3 < 0.05um")
#
if geomNumShapes(via4) > 0 :
    print("Checking Via4 rules:")
    geomAllowedSize(via4, [[0.19, 0.19]], "V4.a: Min. and max. Via4 width = 0.19um")
    geomSpace(via4, 0.22, "V4.b: Min. Via4 space < 0.22um")
    v4 = geomSize(via4, 0.143)
    v4 = geomSize(v4, -0.238)
    v4 = geomSize(v4, 0.095)
    v4 = geomSize(v4, -0.505)
    v4 = geomSize(v4, 0.505)
    saveDerived(v4, "V4.b1: Min. Via4 space in an array of more than 3 rows and more then 3 columns  < 0.29um")
    geomEnclose(metal3, via4, 0.005, "V4.c: Min. Metal4 enclosure of Via4 < 0.005um")
    geomExtension(metal3, via4, 0.05, "V4.c1: Min. Metal4 endcap enclosure of Via4 < 0.05um")
#
if geomNumShapes(topvia1) > 0 :
    print("Checking TopVia1 rules:")
    geomAllowedSize(topvia1, [[0.42, 0.42]], "TV1.a: Min. and max. TopVia1 width != 0.42um")
    geomSpace(topvia1, 0.42, "TV1.b: Min. TopVia1 space < 0.42um")
    geomEnclose(metal5, topvia1, 0.10, "TV1.c: Min. Metal5 enclosure of TopVia1 < 0.10um")
    geomEnclose(topmetal1, topvia1, 0.42, "TV1.d: Min. TopMetal1 enclosure of TopVia1 < 0.42um")
#
if geomNumShapes(topmetal1) > 0 :
    print("Checking TopMetal1 rules:")
    geomWidth(topmetal1, 1.64, "TM1.a: Min. TopMetal1 width < 1.64um")
    geomSpace(topmetal1, 1.64, "TM1.b: Min. TopMetal1 space or notch < 1.64um")
    geomNotch(topmetal1, 1.64, "TM1.b: Min. TopMetal1 space or notch < 1.64um")
    geomMinDensity(topmetal1, 25.00, "TM1.c: Min. global TopMetal1 density [%] < 25.00%")
    geomMaxDensity(topmetal1, 70.00, "TM1.d: Max. global TopMetal1 density [%] > 70.00%")
#
if geomNumShapes(topmetal1_filler) > 0 :
    print("Checking TopMetal1:filler rules:")
    geomWidth(topmetal1_filler, 5.00, "TM1Fil.a: Min. TopMetal1:filler width < 5.00um")
    saveDerived(geomSize(geomSize(topmetal1_filler, -5, horizontal), 5, horizontal), "TM1Fil.a1: Max. TopMetal1:filler width > 10.00um")
    saveDerived(geomSize(geomSize(topmetal1_filler, -5, vertical), 5, vertical), "TM1Fil.a1: Max. TopMetal1:filler width > 10.00um")
    geomSpace(topmetal1_filler, 3.00, "TM1Fil.b: Min. TopMetal1:filler space < 3.00um")
    geomSpace(topmetal1_filler, topmetal1, 3.0, "TM1Fil.c: Min. TopMetal1:filler space to TopMetal1 < 3.00um")
    geomSpace(topmetal1_filler, trans, 4.90, "TM1Fil.d: Min. TopMetal1:filler space to TRANS < 4.90um")
#
if geomNumShapes(topvia2) > 0 :
    print("Checking TopVia2 rules:")
    geomAllowedSize(topvia2, [[0.90, 0.90]], "TV2.a: Min. and max. TopVia2 width != 0.90um")
    geomSpace(topvia2, 1.06, "TV2.b: Min. TopVia2 space < 1.06um")
    geomEnclose(topmetal1, topvia2, 0.50, "TV2.c: Min. TopMetal1 enclosure of TopVia2 < 0.50um")
    geomEnclose(topmetal2, topvia2, 0.50, "TV2.d: Min. TopMetal2 enclosure of TopVia2 < 0.50um")
#
if geomNumShapes(topmetal2) > 0 :
    print("Checking TopMetal2 rules:")
    geomWidth(topmetal2, 2.00, "TM2.a: Min. TopMetal2 width < 2.00um")
    geomSpace(topmetal2, 2.00, "TM2.b: Min. TopMetal2 space or notch < 2.00um")
    geomNotch(topmetal2, 2.00, "TM2.b: Min. TopMetal2 space or notch < 2.00um")
    geomSpace(topmetal2, 5.00, 5.00, 50.00, parallel, "TM2.bR: Min. space of TopMetal2 lines if, at least one line is wider than 5.0um and the parallel run is more than 50.0um < 5.00um")
    geomMinDensity(topmetal2, 25.00, "TM2.c: Min. global TopMetal2 density [%] < 25.00%")
    geomMaxDensity(topmetal2, 70.00, "TM2.d: Max. global TopMetal2 density [%] > 70.00%")
#
if geomNumShapes(topmetal2_filler) > 0 :
    print("Checking TopMetal2:filler rules:")
    geomWidth(topmetal2_filler, 5.00, "TM2Fil.a: Min. TopMetal2:filler width < 5.00um")
    saveDerived(geomSize(geomSize(topmetal2_filler, -5, horizontal), 5, horizontal), "TM2Fil.a1: Max. TopMetal2:filler width > 10.00um")
    saveDerived(geomSize(geomSize(topmetal2_filler, -5, vertical), 5, vertical), "TM2Fil.a1: Max. TopMetal2:filler width > 10.00um")
    geomSpace(topmetal2_filler, 3.00, "TM2Fil.b: Min. TopMetal2:filler space < 3.00um")
    geomSpace(topmetal2_filler, topmetal2, 3.0, "TM2Fil.c: Min. TopMetal2:filler space to TopMetal2 < 3.00um")
    geomSpace(topmetal2_filler, trans, 4.90, "TM2Fil.d: Min. TopMetal2:filler space to TRANS < 4.90um")
#
if geomNumShapes(passiv) > 0 :
    print("Checking Passiv rules:")
    geomWidth(passiv, 2.10, "Pas.a: Min. Passiv width < 2.10um")
    geomSpace(passiv, 3.50, "Pas.b: Min. Passiv space or notch < 3.50um")
    geomNotch(passiv, 3.50, "Pas.b: Min. Passiv space or notch < 3.50um")
    geomEnclose(topmetal2, passiv, 2.10, "Pas.c: Min. TopMetal2 enclosure of Passiv < 2.10um")
#
if geomNumShapes(nres) > 0 :
    print("Checking Rsil rules:")
    geomWidth(nres, 0.50, "Rsil.a: Min. GatPoly width < 0.50um")
    geomSpace(res, cont, 0.12, "Rsil.b: Min. RES space to Cont < 0.12um")
    geomExtension(res, gatpoly, 0.00, "Rsil.c: Min. RES extension over GatPoly < 0.00um")
    geomSpace(psd, nres, 0.18, "Rsil.d: Min. pSD space to GatPoly < 0.18um")
    geomEnclose(extblock, geomInteracts(nres, gatpoly), 0.18, "Rsil.e: Min. EXTBlock enclosure of GatPoly < 0.18um")
    geomLength(res, 0.50, "Rsil.f: Min. RES length < 0.50um")
#
if geomNumShapes(pres) > 0 :
    print("Checking Rppd rules:")
    geomWidth(pres, 0.50, "Rppd.a: Min. GatPoly width < 0.50um")
    geomEnclose(psd, geomInteracts(pres, gatpoly), 0.18, "Rppd.b: Min. pSD enclosure of GatPoly < 0.18um")
    geomSpace(salblcok, geomAnd(cont, geomInteracts(pres, gatpoly)), 0.20, not_equal, "Rppd.c: Min. and max. SalBlock space to Cont != 0.20um")
    geomEnclose(extblock, geomInteracts(pres, gatpoly), 0.18, "Rppd.d: Min. EXTBlock enclosure of GatPoly < 0.18um")
    geomLength(geomInteracts(pres, salblcok), 0.50, "Rppd.e: Min. SalBlock length < 0.50um")
#
if geomNumShapes(pnres) > 0 :
    print("Checking Rhigh rules:")
    geomWidth(pnres, 0.50, "Rhi.a: Min. GatPoly width < 0.50um")
    saveDerived(geomAndNot(nsd, psd), "Rhi.b: pSD and nSD are identical")
    geomEnclose(geomOr(psd, nsd), geomInteracts(pnres, gatpoly), 0.18, "Rhi.c: Min. pSD and nSD enclosure of GatPoly < 0.18um")
    geomSpace(salblcok, geomAnd(cont, geomInteracts(pnres, gatpoly)), 0.20, not_equal, "Rhi.d: Min. and max. SalBlock space to Cont != 0.20um")
    geomEnclose(extblock, geomInteracts(pnres, gatpoly), 0.18, "Rhi.e: Min. EXTBlock enclosure of GatPoly < 0.18um")
    geomLength(geomInteracts(pnres, salblcok), 0.50, "Rhi.f: Min. SalBlock length < 0.50um")
#
if ((geomNumShapes(infet) > 0) or (geomNumShapes(hvinfet) > 0)) :
    print("Checking inmos and inmosHV rules:")
    geomEnclose(nbl, geomContains(geomContains(nbl, pwell), activ), 1.24, "nmosi.b: Min. nBuLay enclosure of Iso-PWell-Activ < 1.24um")
    geomSpace(nwell, geomContains(geomContains(nbl, pwell), activ), 0.39, "nmosi.c: Min. NWell space to Iso-PWell-Activ < 0.39um")
    geomWidth(geomTouching(geomContains(nbl, pwell), nwell), 0.62, "nmosi.d: Min. NWell-nBuLay width forming an unbroken ring around any Iso-PWell-Activ < 0.62um")
    saveDerived(geomNotTouching(geomTouching(geomOr(infet, hvinfet), nactiv), geomAndNot(ptap, digibnd)), "nmosi.e1: A separate Iso-PWell contact unabutted to a nmosi device is not allowed")
    saveDerived(geomNotTouching(ptap, geomTouching(geomOr(infet, hvinfet), geomAndNot(nactiv, digibnd))), "nmosi.e2: nmosi unabutted to an Iso-PWell-Activ tie is not allowed")
    geomWidth(geomAnd(geomContains(nbl, pwell), nsd_block), 0.62, "nmosi.f: Min. nSD:block width to separate ptap in nmosi < 0.62um")
    geomOverlap(salblcok, geomAnd(geomAnd(geomContains(nbl, pwell), nsd_block), activ), 0.15, "nmosi.f: Min. SalBlock overlap of nSD:block over Activ < 0.15um")
#
if geomNumShapes(schottky) > 0 :
    print("Checking Schottky diode rules:")
    geomEnclose(geomContains(pwell_block, schottky, layer1), schottky, 0.25, not_equal, "Sdiod.a: Min. and max. PWell:block enclosure of ContBar != 0.25um")
    geomEnclose(geomContains(nsd_block, schottky, layer1), schottky, 0.40, not_equal, "Sdiod.b: Min. and max. nSD:block enclosure of ContBar != 0.40um")
    geomEnclose(geomContains(salblcok, schottky, layer1), schottky, 0.45, not_equal, "Sdiod.c: Min. and max. SalBlock enclosure of ContBar != 0.40um")
    geomAllowedWidths(schottky, [0.30], horizontal | vertical, "Sdiod.d: Min. and max. ContBar width inside nBuLay != 0.30um")
    geomLength(schottky, 1.00, not_equal, "Sdiod.e: Min. and max. ContBar length inside nBuLay != 1.00um")
#
if ((geomNumShapes(pad) > 0) or (geomNumShapes(sbumppad) > 0) or (geomNumShapes(cupillarpad) > 0)) :
    print("Checking Pad rules:")
    geomWidth(pad, 30.00, lessthan, "Pad.aR: Min. recommended Pad width < 30.00um")
    saveDerived(geomSize(geomSize(pad, -75.00), 75.00), "Pad.a1: Max. Pad width > 150.00um")
    geomSpace(pad, 8.40, "Pad.bR: Min. recommended Pad space < 8.40um")
    geomSpace(pad, edgeseal, 7.50, "Pad.d: Min. Pad space to EdgeSeal < 7.50um")
    geomSpace(pad, edgeseal, 25.00, "Pad.dR: Min. recommended Pad to EdgeSeal space < 25.00um")
    geomSpace(pad, geomContains(geomSize(geomSize(geomSize(edgeseal, 1e5), -1e5), -3.50), activ), 11.20, "Pad.d1R: Min. recommended Pad to Activ (inside chip area) space < 11.20um")
    geomWidth(geomTouching(dpad, geomOr(metal1, geomOr(metal2, geomOr(metal3, geomOr(metal4, geomOr(metal5, geomOr(topmetal1, topmetal2))))))), 7.00, "Pad.eR: Min. recommended Metal(n), TopMetal1, TopMetal2 exit width < 7.00um")
    geomLength(geomTouching(dpad, geomOr(metal1, geomOr(metal2, geomOr(metal3, geomOr(metal4, geomOr(metal5, geomOr(topmetal1, topmetal2))))))), 7.00, "Pad.fR: Min. recommended Metal(n), TopMetal1, TopMetal2 exit length < 7.00um")
    geomEnclose(geomInside(dpad, topmetal1), topvia2, 1.40, "Pad.gR: Min. recommended TopMetal1 (within dfpad) enclosure of TopVia2 < 1.40um")
    saveDerived(geomAndNot(dpad, topmetal2), "Pad.i: dfpad without TopMetal2 not allowed")
    saveDerived(geomAnd(pad, geomOr(nfet, geomOr(pfet, geomOr(nres, geomOr(pres, geomOr(pnres, schottky)))))), "Pad.jR: No devices under Pad allowed")
    saveDerived(geomAnd(pad, topvia2), "Pad.kR: TopVia2 under Pad not allowed")
#
if geomNumShapes(sbumppad) > 0 :
    print("Checking Solder Bump Rules rules:")
    geomAllowedSize(sbumppad, [[60.00, 60.00]], "Padb.a: SBumpPad size != 60.00um")
    geomSpace(sbumppad, 70.00, "Padb.b: Min. SBumpPad space < 70.00um")
    geomEnclose(geomContains(dpad, topmetal2), sbumppad, 10.00, "Padb.c: Min. TopMetal2 (within dfpad) enclosure of SBumpPad < 10.00um")
    geomSpace(sbumppad, edgeseal, 50.00, "Padb.d: Min. SBumpPad space to EdgeSeal  < 50.00um")
    geomPitch(sbumppad, 130.00, vertical | horizontal | diagonal, "Padb.e : Min. SBumpPad pitch != 130.00um")
#
if geomNumShapes(cupillarpad) > 0 :
    print("Checking Copper Pillar Rules rules:")
    geomAllowedSize(cupillarpad, [[35.00, 35.00], [40.00, 40.00], [45.00, 45.00]], "Padc.a: CuPillarPad size != 35.00um or 40.00um or 45.00um")
    geomSpace(cupillarpad, 40.00, "Padc.b: Min. CuPillarPad space for 35um and 40um size < 40.00um")
    geomSpace(geomSize(geomSize(cupillarpad, -21.00), 21.00), 50.00, "Padc.b: Min. CuPillarPad space for 45um size < 50.00um")
    geomEnclose(geomContains(dpad, topmetal2), cupillarpad, 7.50, "Padc.c: Min. TopMetal2 (within dfpad) enclosure of CuPillarPad < 7.50um")
    geomSpace(cupillarpad, edgeseal, 30.00, "Padb.d: Min. CuPillarPad space to EdgeSeal  < 30.00um")
    geomPitch(cupillarpad, 75.00, vertical | horizontal | diagonal, "Padb.e : Min. CuPillarPad pitch != 75.00um")
    geomPitch(geomSize(geomSize(cupillarpad, -18.00), 18.00), 80.00, vertical | horizontal | diagonal, "Padb.e : Min. CuPillarPad pitch != 80.00um")
    geomPitch(geomSize(geomSize(cupillarpad, -21.00), 21.00), 95.00, vertical | horizontal | diagonal, "Padb.e : Min. CuPillarPad pitch != 85.00um")
#
if geomNumShapes(edgeseal) > 0 :
    print("Checking Sealring Rules rules:")
    geomWidth(geomAnd(edgeseal, activ), 3.50, "Seal.a: Min. EdgeSeal-Activ, EdgeSeal-pSD, EdgeSeal-Metal(n=1-5), EdgeSeal-TopMetal1, EdgeSeal-TopMetal2 width < 3.50um")
    geomWidth(geomAnd(edgeseal, psd), 3.50, "Seal.a: Min. EdgeSeal-Activ, EdgeSeal-pSD, EdgeSeal-Metal(n=1-5), EdgeSeal-TopMetal1, EdgeSeal-TopMetal2 width < 3.50um")
    geomWidth(geomAnd(edgeseal, metal1), 3.50, "Seal.a: Min. EdgeSeal-Activ, EdgeSeal-pSD, EdgeSeal-Metal(n=1-5), EdgeSeal-TopMetal1, EdgeSeal-TopMetal2 width < 3.50um")
    geomWidth(geomAnd(edgeseal, metal2), 3.50, "Seal.a: Min. EdgeSeal-Activ, EdgeSeal-pSD, EdgeSeal-Metal(n=1-5), EdgeSeal-TopMetal1, EdgeSeal-TopMetal2 width < 3.50um")
    geomWidth(geomAnd(edgeseal, metal3), 3.50, "Seal.a: Min. EdgeSeal-Activ, EdgeSeal-pSD, EdgeSeal-Metal(n=1-5), EdgeSeal-TopMetal1, EdgeSeal-TopMetal2 width < 3.50um")
    geomWidth(geomAnd(edgeseal, metal3), 3.50, "Seal.a: Min. EdgeSeal-Activ, EdgeSeal-pSD, EdgeSeal-Metal(n=1-5), EdgeSeal-TopMetal1, EdgeSeal-TopMetal2 width < 3.50um")
    geomWidth(geomAnd(edgeseal, metal5), 3.50, "Seal.a: Min. EdgeSeal-Activ, EdgeSeal-pSD, EdgeSeal-Metal(n=1-5), EdgeSeal-TopMetal1, EdgeSeal-TopMetal2 width < 3.50um")
    geomWidth(geomAnd(edgeseal, topmetal1), 3.50, "Seal.a: Min. EdgeSeal-Activ, EdgeSeal-pSD, EdgeSeal-Metal(n=1-5), EdgeSeal-TopMetal1, EdgeSeal-TopMetal2 width < 3.50um")
    geomWidth(geomAnd(edgeseal, topmetal2), 3.50, "Seal.a: Min. EdgeSeal-Activ, EdgeSeal-pSD, EdgeSeal-Metal(n=1-5), EdgeSeal-TopMetal1, EdgeSeal-TopMetal2 width < 3.50um")
    geomSpace(geomAnd(edgeseal, activ), geomAndNot(activ, edgeseal), 4.90, "Seal.b: Min. Activ space to EdgeSeal-Activ, EdgeSeal-pSD, EdgeSeal-Metal(n=1-5), EdgeSeal-TopMetal1, EdgeSeal-TopMetal2 < 4.90um")
    geomWidth(geomAnd(edgeseal, cont), 0.16, "Seal.c: EdgeSeal-Cont ring width < 0.16um")
    geomWidth(geomAnd(edgeseal, geomOr(via1, geomOr(via2, geomOr(via3, via4)))), 0.19, "Seal.c1: EdgeSeal-Via(n=1-4) ring width < 0.19um")
    geomWidth(geomAnd(edgeseal, topvia1), 0.42, "Seal.c2: EdgeSeal-TopVia1 ring width < 0.42um")
    geomWidth(geomAnd(edgeseal, topvia2), 0.90, "Seal.c3: EdgeSeal-TopVia2 ring width < 0.90um")
    geomEnclose(geomAnd(edgeseal, activ), geomAnd(edgeseal, (geomOr(cont, geomOr(via1, geomOr(via2, geomOr(via3, geomOr(via4, geomOr(topvia1, topvia2)))))))), 1.30, "Seal.d: Min. EdgeSeal-Activ enclosure of EdgeSeal-Cont, EdgeSeal-Via(n=1-4), EdgeSeal-TopVia1, EdgeSeal-TopVia2 ring < 1.30um")
    geomWidth(geomOutside(geomSize(geomSize(edgeseal, 1e5), -1e5), passiv), 4.20, "Seal.e: Min. Passiv ring width outside of sealring < 4.20um")
    geomSpace(geomOutside(geomSize(geomSize(edgeseal, 1e5), -1e5), passiv), edgeseal, 1.00, "Seal.f: Min. Passiv ring outside of sealring space to EdgeSeal-Activ, EdgeSeal-Metal(n=1-5), EdgeSeal-TopMetal1, EdgeSeal-TopMetal2 < 1.00um")
#
if geomNumShapes(mimcap) > 0 :
    print("Checking MIM rules:")
    geomWidth(mimcap, 1.14, "MIM.a: Min. MIM width < 1.14um")
    geomSpace(mimcap, 0.60, "MIM.b: Min. MIM space < 0.60um")
    geomEnclose(metal5, mimcap, 0.60, "MIM.c: Min. Metal5 enclosure of MIM < 0.60um")
    geomEnclose(mimcap, topvia1, 0.36, "MIM.d: Min. MIM enclosure of TopVia1 < 0.36um")
    geomSpace(mimcap, topmetal1, 0.60, "MIM.e: Min. TopMetal1 space to MIM < 0.60um")
    geomArea(mimcap, 1.30, lessthan, "MIM.f: Min. MIM area per MIM device (um^2) < 1.30um^2") 
    geomArea(mimcap, 5625.00, greaterthan, "MIM.g: Max. MIM area per MIM device (um^2) < 5625.00um^2") 
    geomArea(geomAnd(bkgnd, mimcap), 174800.00, greaterthan, "MIM.gR: Max. recommended total MIM area per chip (um^2) < 174800.00um^2") 
    saveDerived(geomNotOverlapping(mimcap, topvia1, layer1), "MIM.h: TopVia1 must be over MIM")
#
if geomNumShapes(metal) > 0 :
    print("Checking Metal Slits rules:")
    geomWidth(metal_slit, 2.80, "Slt.a: Min. Metal:slit width < 2.80um")
    saveDerived(geomSize(geomSize(metal_slit, -10.00), 10.00), "Slt.b: Max. Metal:slit width > 20.00um")
    saveDerived(geomSize(geomSize(geomAndNot(metal1, metal1_slit), -15.00), 15.00), "Slt.c: Max. Metal1 width without requiring a Metal1:slit > 30.00um")
    saveDerived(geomSize(geomSize(geomAndNot(metal2, metal2_slit), -15.00), 15.00), "Slt.c: Max. Metal2 width without requiring a Metal2:slit > 30.00um")
    saveDerived(geomSize(geomSize(geomAndNot(metal3, metal3_slit), -15.00), 15.00), "Slt.c: Max. Metal3 width without requiring a Metal3:slit > 30.00um")
    saveDerived(geomSize(geomSize(geomAndNot(metal4, metal4_slit), -15.00), 15.00), "Slt.c: Max. Metal4 width without requiring a Metal4:slit > 30.00um")
    saveDerived(geomSize(geomSize(geomAndNot(metal5, metal5_slit), -15.00), 15.00), "Slt.c: Max. Metal5 width without requiring a Metal5:slit > 30.00um")
    saveDerived(geomSize(geomSize(geomAndNot(topmetal1, topmetal1_slit), -15.00), 15.00), "Slt.c: Max. TopMetal1 width without requiring a TopMetal1:slit > 30.00um")
    saveDerived(geomSize(geomSize(geomAndNot(geomAndNot(topmetal2, geomOr(pad, geomOr(sbumppad, cupillarpad))), topmetal2_slit), -15.00), 15.00), "Slt.c: Max. TopMetal2 width without requiring a TopMetal2:slit > 30.00um")
    geomEnclose(metal1, metal1_slit, 1.00, "Slt.f: Min. Metal1 enclosure of Metal1:slit < 1.00um")
    geomEnclose(metal2, metal2_slit, 1.00, "Slt.f: Min. Metal2 enclosure of Metal2:slit < 1.00um")
    geomEnclose(metal3, metal3_slit, 1.00, "Slt.f: Min. Metal3 enclosure of Metal3:slit < 1.00um")
    geomEnclose(metal4, metal4_slit, 1.00, "Slt.f: Min. Metal4 enclosure of Metal4:slit < 1.00um")
    geomEnclose(metal5, metal5_slit, 1.00, "Slt.f: Min. Metal1 enclosure of Metal5:slit < 1.00um")
    geomEnclose(topmetal1, topmetal1_slit, 1.00, "Slt.f: Min. TopMetal1 enclosure of TopMetal1:slit < 1.00um")
    geomEnclose(topmetal2, topmetal2_slit, 1.00, "Slt.f: Min. TopMetal2 enclosure of TopMetal2:slit < 1.00um")
    geomSpace(geomOr(metal5_slit, topmetal1_slit), mimcap, 0.60, "Slt.g: Min. Metal5:slit and TopMetal1:slit space to MIM < 0.60um")
    geomSpace(metal1_slit, geomOr(cont, via1), 0.30, "Slt.h1: Min. Metal1:slit space to Cont and Via1 < 0.30um")
    geomSpace(metal2_slit, geomOr(via1, via2), 0.30, "Slt.h2: Min. Metal2:slit space to Via1 and Via2 < 0.30um")
    geomSpace(metal3_slit, geomOr(via2, via3), 0.30, "Slt.h2: Min. Metal3:slit space to Via2 and Via4 < 0.30um")
    geomSpace(metal4_slit, geomOr(via3, via4), 0.30, "Slt.h2: Min. Metal4:slit space to Via3 and Via5 < 0.30um")
    geomSpace(metal5_slit, geomOr(via4, topvia1), 0.30, "Slt.h2: Min. Metal5:slit space to Via4 and TopVia1 < 0.30um")
    geomSpace(topmetal1_slit, geomOr(topvia1, topvia2), 1.00, "Slt.h3: Min. TopMetal1:slit space to TopVia1 and TopVia2 < 1.00um")
    geomSpace(topmetal2_slit, topvia2, 1.00, "Slt.h4: Min. TopMetal2:slit space to TopVia2 < 1.00um")
    geomMinDensity(geomContains(geomSize(geomSize(metal1, -17.50), 17.50), metal1_slit), 6.00, "Slt.i: Min. Metal1:slit density for any Metal1 plate bigger than 35um x 35um [%] < 6.00%")
    geomMinDensity(geomContains(geomSize(geomSize(metal2, -17.50), 17.50), metal2_slit), 6.00, "Slt.i: Min. Metal2:slit density for any Metal2 plate bigger than 35um x 35um [%] < 6.00%")
    geomMinDensity(geomContains(geomSize(geomSize(metal3, -17.50), 17.50), metal3_slit), 6.00, "Slt.i: Min. Metal3:slit density for any Metal3 plate bigger than 35um x 35um [%] < 6.00%")
    geomMinDensity(geomContains(geomSize(geomSize(metal4, -17.50), 17.50), metal4_slit), 6.00, "Slt.i: Min. Metal4:slit density for any Metal4 plate bigger than 35um x 35um [%] < 6.00%")
    geomMinDensity(geomContains(geomSize(geomSize(metal5, -17.50), 17.50), metal5_slit), 6.00, "Slt.i: Min. Metal5:slit density for any Metal5 plate bigger than 35um x 35um [%] < 6.00%")
    geomMinDensity(geomContains(geomSize(geomSize(topmetal1, -17.50), 17.50), topmetal1_slit), 6.00, "Slt.i: Min. TopMetal1:slit density for any TopMetal1 plate bigger than 35um x 35um [%] < 6.00%")
    geomMinDensity(geomContains(geomSize(geomSize(topmetal2, -17.50), 17.50), topmetal2_slit), 6.00, "Slt.i: Min. TopMeta2:slit density for any TopMetal2 plate bigger than 35um x 35um [%] < 6.00%")
#
if geomNumShapes(pin) > 0 :
    print("Checking Pin Layer rules:")
    saveDerived(geomAndNot(activ_pin, activ), "Pin.a: Min. Activ enclosure of Activ:pin != 0.00")
    saveDerived(geomAndNot(gatpoly_pin, gatpoly_pin), "Pin.b: Min. GatPoly enclosure of GatPoly:pin != 0.00")
    saveDerived(geomAndNot(metal1_pin, metal1), "Pin.e: Min. Metal1 enclosure of Metal1:pin != 0.00")
    saveDerived(geomAndNot(metal1_pin, metal2), "Pin.f: Min. Metal2 enclosure of Metal2:pin != 0.00")
    saveDerived(geomAndNot(metal1_pin, metal3), "Pin.f: Min. Metal3 enclosure of Metal3:pin != 0.00")
    saveDerived(geomAndNot(metal1_pin, metal4), "Pin.f: Min. Metal4 enclosure of Metal4:pin != 0.00")
    saveDerived(geomAndNot(metal1_pin, metal5), "Pin.f: Min. Metal5 enclosure of Metal5:pin != 0.00")
    saveDerived(geomAndNot(topmetal1_pin, topmetal1), "Pin.g: Min. TopMetal1 enclosure of TopMetal1:pin != 0.00")
    saveDerived(geomAndNot(topmetal2_pin, topmetal2), "Pin.h: TopMetal2 enclosure of TopMetal2:pin != 0.00")
#
if geomNumShapes(digibnd) > 0 :
    print("Checking DigiBnd Layer rules:")
    geomEnclose(nwell, geomInside(digibnd, thickpactiv), 0.31, "NW.c1: Min. NWell enclosure of P+Activ inside ThickGateOx inside DigiBnd < 0.31um")
    geomSpace(nwell, geomInside(digibnd, thicknactiv), 0.31, "NW.d1: Min. NWell space to external N+Activ inside ThickGateOx inside DigiBnd < 0.31um")
    geomEnclose(nwell, geomInside(digibnd, thickntap), 0.24, "NW.e1: Min. NWell enclosure of NWell tie surrounded entirely by NWell in N+Activ inside ThickGateOx inside DigiBnd < 0.24um")
    geomSpace(nwell, geomInside(digibnd, thickptap), 0.24, "NW.f1:  Min. NWell space to substrate tie in P+Activ inside ThickGateOx inside DigiBnd < 0.24um")
    geomEnclose(activ, geomInside(digibnd, cnt), 0.05, "Cnt.c: Min. Activ enclosure of Cont inside DigiBnd < 0.05um")
#
if geomNumShapes(lbe) > 0 :
    print("Checking Localized Backside Etching (LBE) rules:")
    geomWidth(lbe, 100.00, "LBE.a: Min. LBE width < 100.00um")
    saveDerived(geomSize(geomSize(lbe, -750.00), 750.00), "LBE.b: Max. LBE width > 1500.00um")
    geomArea(lbe, 250000.00, greaterthan, "LBE.b1: Max. LBE area (um^2) > 250000.00um^2")
    geomArea(lbe, 30000.00, lessthan, "LBE.b1: Min. LBE area (um^2) > 30000.00um^2")
    geomSpace(lbe, 100.00, "LBE.c: Min. LBE space or notch < 100.00um")
    geomNotch(lbe, 100.00, "LBE.c: Min. LBE space or notch < 100.00um")
    geomEnclose(geomSize(geomSize(geomSize(edgeseal, 1e5), -1e5), -3.50), lbe, 150.00, "LBE.d: Min. LBE space to inner edge of EdgeSeal < 150.00um")
    geomSpace(lbe, geomOr(dpad, passiv), 50.00, "LBE.e: Min. LBE space to dfpad and Passiv < 50.00um")
    geomSpace(lbe, geomAndNot(activ, edgeseal), 30.00, "LBE.f: Min. LBE space to Activ < 30.00um")
    saveDerived(geomHoles(lbe), "No LBE ring allowed")
    geomMaxDensity(lbe, 20.00, "LBE.i: Max. global LBE density [%] < 20.00%")
#
# Showing number of errors
#
# num_errors = geomGetTotalCount()
# if num_errors==0:
#     print ("No DRC errors were found.")
# else:
#     print ("Found {0!s} DRC error{1}.".format(num_errors, 's' if num_errors>1 else ''))
#
# Exiting DRC
#
geomEnd()
#
# Marking the errors
#
ui().winRedraw()
